### ISSUE TITLE
function signatures and full docs

### ISSUE THREAD

**Issue by FernandoBasso** [ternjs/tern_for_vim#115]
Should _tern_for_vim_ give me hints for function/method signatures? If so, it is not working here, and I must dig into the problem then. Also, should `TernDoc` provide the full docs, including `@param`, etc, or just the basic description of the function? It just shows me the "first line" of the docs here. I'm using JSDoc style documentation.

**Comment by marijnh** [comment]
tern_for_vim's TernDoc will provide you with the first sentence of the docstring. Plugins can also ask for the full docstring, but tern_for_vim doesn't currently do so.
