### ISSUE TITLE
[idea] Lazy load things.

### ISSUE THREAD

**Issue by trusktr** [ternjs/tern_for_vim#120]
This plugin makes loading a bunch of JavaScript files really slow (suppose we're loading a session file with 20 JavaScript files to open).

Idea: Make tern only load what's needed when a Tern* command is first executed.

**Comment by marijnh** [comment]
This was actually the intended behavior all along, but it looks like I screwed something up when writing the Vim plugin. Could you see whether attached patch fixes it for you?
