### ISSUE TITLE
2 issuse about auto complte

### ISSUE THREAD

**Issue by lookforit** [ternjs/tern_for_vim#121]
Hi

I tried this plugin and it is really awesome!
However,I have two concerns about how to  set the `.tern-project` file in  nodejs development. 

1. If I installed new packages via `npm`(global or local in project),how can I tell tern_for_vim  to auto complete items in that package?

2. If I switched to a newer version of node, how to make  `tern_for_vim` to auto complete the item that does not exist in the older version of node,but is included in the newer version?
    For example, I have installed 2 version of node:
   * 0.10.xx
   * 4.4.2

  In `0.10.xx`,the `execSync` is unavailable,but it should appear in the `4.x` version when I pressed `dot` after `require` statement: 
```js
 var execSync = require( 'child_process' ).execSync;
```
So pls let me know the way to configure `.tern-project` for these two  scenarios.

Thanks.

**Comment by marijnh** [comment]
> If I installed new packages via npm(global or local in project),how can I tell tern_for_vim to auto complete items in that package?

Configure your project to enable the `node` or just the `node_resolve` (if you don't actually use node, just the `node_modules` convention). For example put this in your `.tern-project` file: `{"plugins": {"node": {}}}`.

> how to make tern_for_vim to auto complete the item that does not exist in the older version of node,but is included in the newer version?

Tern doesn't version libraries, it tries to just reflect a recent version of the API. So if you're missing stuff from node 4, you can submit pull requests that update `plugin/node.js` to add those items.

**Comment by lookforit** [comment]
Thanks for your  reply.
Yes,if Ｉ placed |.tern-project file in project  directory, tern can 
find the modules located  in node_modules directory,then auto  complete 
members in that module.
But the  above doesn't work for global  installed modules,that's to say:
npm install -g xxx

xxx module can't be listed in the popup menu.

Am I missing some configuration options?
|
在 2015/12/7 23:29, Marijn Haverbeke 写道:

**Comment by marijnh** [comment]
The way Tern was resolving modules didn't take global paths into account. [This patch](https://github.com/ternjs/tern/commit/44a31f31010e238949c88b1e89698538564f76f2) fixes that.

**Comment by lookforit** [comment]
Thanks ,and  when will these patched release be published to `npm`?

**Comment by marijnh** [comment]
They are on npm now (Tern version 0.17.0)
