### ISSUE TITLE
type validate

### ISSUE THREAD

**Issue by yotamN** [ternjs/tern_for_vim#124]
Tern can know what type every parameter and variable is by jsdoc. So what about checking if function calls are correct with tern_for_vim? Here is a simple example:
```
/**
 * this is a description
 * @param {String} s - a string
 */
function test(s) {
  // do something
}

test(1); // throw a warning
```

Is it possible/planned?

**Comment by marijnh** [comment]
Validation is explicitly out of scope for Tern. It could do something like that with JSDoc annotations, but for types it inferred itself it would not work, and I don't want to take the project in that direction (it'd be a whole lot of new problems to solve). You might be interested in the [tern-lint project](https://github.com/angelozerr/tern-lint), or tools like [TypeScript](http://www.typescriptlang.org/) and [Flow](http://flowtype.org/).
