### ISSUE TITLE
Deoplete support

### ISSUE THREAD

**Issue by carlitux** [ternjs/tern_for_vim#130]
Hi,

I am using deoplete/neovim/ternjs and is using a lot of CUP please take a look https://github.com/Shougo/deoplete.nvim/issues/180

**Comment by bbatha** [comment]
:+1:

**Comment by carlitux** [comment]
I just migrated code to use with deoplete... if anyone interested on test and report bugs would be good. 
https://github.com/carlitux/deoplete-ternjs

**Comment by chemzqm** [comment]
I have the same issue when editing jsx files, I thinks that's because tern doesn't support jsx syntax, I've tried to use acorn-jsx to replace acorn that used by tern, and the problem is gone.
