### ISSUE TITLE
References Not Found When Plugins Are Used

### ISSUE THREAD

**Issue by git-blame** [ternjs/tern_for_vim#139]
If I have 2 files _api.js_ and _app.js_, then using _:TernRef_ works globally for **myFunc** if I have no plugins in my _.tern-project_ file. I assume based simply on identifier matching. Note I have specified **loadEagerly** on the two files.

**api.js**:
```
export function myFunc() {
  return 10;
}

export function myFunc2() {
  return myFunc() + 10;
}
```

**app.js**:
```
import myFunc from './api';
export function myapp() {
  return myFunc();
}
```

But if I include plugins such as _node_, _modules_, and _es_modules_, then references are only found within a file. For example, **:TernRef** in file _api.js_ only shows that **myFunc** is used in **myFunc2**.

Is there a way I can get tern to continue doing global matches and/or using all of the _import_ information across all files to find references?

I'm running vim v7.4 (homebrew) on the Mac with tern v0.18.0 and node v0.12.4.

**Comment by marijnh** [comment]
If you enable a plugin that introduces a module system, files will be wrapped in modules, and thus won't add to the global scope. This is how those module systems work, so that's working as intended.

**Comment by git-blame** [comment]
For example, I have a project that uses the _node_ module **immutable**. I have several files that import the function **fromJS** from this module for use. I thought that I can query **:TernDef** on _fromJS_ to find all files that use this function (and even more specifically from _immutable_) based on the import declarations similar to import references in other languages.

It looks like I have to omit all plugins if I want this behaviour.

**Comment by marijnh** [comment]
Ah, I see what you mean now. You should be able to run :TernDef multiple time to continue jumping through imports.

**Comment by git-blame** [comment]
Sorry, I'm new to tern so I'm not sure the right sequence to use or what it supports. Suppose I'm in a file like this:

**foobar.js**:
```javascript
import { fromJS } from 'immutable';
...
export function foobar() {
  return fromJS({ foo: 1, bar: 1 });
}
```

If I :TernDef _fromJS_ in _foobar_, I go to `import { fromJS }`. That's good. If I :TernDef that, I go to a file in the _immutable_ module. This is all good.

But if I use :TernRef on _fromJS_, it doesn't matter if it's in function _foobar_, the _import_ statement, or the function _fromJS_ inside the immutable module, I only get the file-local references.

I really thought that when I use :TernRef on fromJS in file foobar.js, tern would recognize that fromJS is from immutable, based on the import statement in file foobar.js, then resolve all files that include fromJS (from immutable) in their import, then all calls to fromJS within those files, and show all these source lines.

I guess I can only get that by omitting plugins and therefore making everything in the global scope. I lose the ability to following import statements or jump inside node modules with :TernDef. But it's more important for me to be aware of or find all uses of a given identifier/function.
