### ISSUE TITLE
Is there any way to find out each completion comes from which libs or plugin?

### ISSUE THREAD

**Issue by dNItro** [ternjs/tern_for_vim#140]
Inspecting `tern_ensureCompletionCached()` function, its data just contains `type`, `doc` and `url` of each completions so is there any way to get the lib (or plugin) that this completions come from. In defs and plugin files its specified by `!name`( i.e : ecma5, ecma6, jQuery, node, ... ). is there any way to retrieve it? may you add a function to do so?

**Comment by marijnh** [comment]
Set the `query.origins` property to `true`, and you'll get an origin string (the file or definition from which a completion comes)

**Comment by Tav0** [comment]
Could you explain where to find `query.origins`? @marijnh
