### ISSUE TITLE
runtimepath

### ISSUE THREAD

**Issue by Ro6afF** [ternjs/tern_for_vim#150]
When i installed the plugin(manually), and i added this line in the .vimrc 
`set runtimepath+=/home/ro6aff/.vim/tern_for_vim`
i sill wasn't able to run this:
`:TernDoc`
Can i get a liitle help?

**Comment by marijnh** [comment]
This seems like a vim question about loading a plugin, not really Tern-specific. I unfortunately know very little about vim, and the only way I know of of using this plugin is with [pathogen](https://github.com/tpope/vim-pathogen).

**Comment by chemzqm** [comment]
@Ro6afF tern command exists only when buffer type is javascript

**Comment by Ro6afF** [comment]
Even when i open .js file thre is no :TernDoc command

**Comment by chemzqm** [comment]
@Ro6afF you should append `PATH_TO_tern_for_vim/after` to your runtime path too.
