### ISSUE TITLE
.tern-port file is not deleted after editing .vimrc or init.vim

### ISSUE THREAD

**Issue by gerardbm** [ternjs/tern_for_vim#153]
Hi!

I'm not sure if it's a bug or simply a config mistake, but `.tern-port` file is deleted as expected after editing any file in any repository, **excepting** `.vimrc` and `init.vim` (both in the same [repository](https://github.com/gerardbm/vimrc/blob/master/init.vim#L261-L263)).

If I open them with neovim (NVIM 0.2.0-dev under GNU/Linux), after inserting text, the `.tern-port` file will be created, the CPU usage will reach 100% and I will have to kill it with `sudo kill -1 {PID}`. 

Any suggestion?

**Comment by chemzqm** [comment]
Tern server should not be started unless you have open any javascript file, is your .vimrc have filetype javascript?

**Comment by gerardbm** [comment]
Yes, through deoplete:

```viml
let g:neocomplete#sources#omni#functions.javascript = [
        \   'jspc#omni',
        \   'tern#Complete',
        \ ]
```
It's equivalent to:
```viml
autocmd FileType javascript setlocal omnifunc=tern#Complete
```
I also tried it with the last one, but the result is the same.

**Comment by chemzqm** [comment]
@gerardbm run `echo &ft` in your vim, if the result not have javascript, tern server should not started.

**Comment by gerardbm** [comment]
As I said, `autocmd Filetype javascript` is ok in my config.

However, I had to remove the plugin [deoplete-ternjs](https://github.com/carlitux/deoplete-ternjs) to fix the issue. I don't know what's happening, the case is that both plugins need to find at least one `.tern-port` file to know where to request, so deoplete-ternjs uses the instance started by tern_for_vim.

It seems there's a conflict into this process under certain cases.

I close the issue because it's fixed after removing an another plugin, despite I'm not sure if it's more related to tern_for_vim or deoplete-ternjs.
