### ISSUE TITLE
Python errors `module 'string' has no attribute 'join'` when doing TernRename

### ISSUE THREAD

**Issue by xc1427** [ternjs/tern_for_vim#154]
I am using windows 10 and vim 8.0 64bit.
Here is the screenshot:
![aa](https://cloud.githubusercontent.com/assets/5611770/21288885/5a69a4ec-c48f-11e6-886e-f0d6ac61060d.PNG)
I am totally sure it is something related to difference between python 2 and python3.
Actually, no errors within python 2. 
But in case of python3, `"".join(lines) ` should be the correct way.

**Comment by marijnh** [comment]
Python 2.7 seems to also support `"".join`. Does attached patch help for you?

**Comment by xc1427** [comment]
> Python 2.7 seems to also support "".join. Does attached patch help for you?

Yes. The patch solves the problem. Effectively, Python 2.7 also supports `"".join`.
