### ISSUE TITLE
Node process is not killed

### ISSUE THREAD

**Issue by albertosantini** [ternjs/tern_for_vim#16]
Node process is not terminated when Vim quits (win7).

I think it is due to this change:
https://github.com/marijnh/tern_for_vim/commit/c48a908e53b477542a5ff2f29bfe3d6419d47137#L0L83

**Comment by vincentwoo** [comment]
This is actually biting me when trying to run tern dockerized - I think Kubernetes ends stdin to the container, which causes tern to kill itself. I'm not sure if this should be a concern, but it took me quite a long time to debug.
