### ISSUE TITLE
tern_for_vim swallowed too much memories

### ISSUE THREAD

**Issue by Gabirel** [ternjs/tern_for_vim#165]
## Environment Information
- OS: Arch Linux
- vim version: 8.0(with `SpaceVim`)

## The reproduce ways from Vim starting
editing any files written by javascript.
And you have to enable `tern_for_vim` and you have to have `.tern-project` or `.tern-config`.
Here's the file:
```json
{
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "**/*.js"
  ],
  "plugins": {
    "node": {}
  }
}
```

1. write `var data = fs`
![image](https://cloud.githubusercontent.com/assets/12933851/24694386/3b4c5dd6-1a14-11e7-9576-5a205af77701.png)

2. add `.` after `fs`(Yes, it's very slow)
![image](https://cloud.githubusercontent.com/assets/12933851/24694468/99b1d392-1a14-11e7-85a6-8d01d27171b6.png)

3. You shall see these:
![image](https://cloud.githubusercontent.com/assets/12933851/24694484/abce2328-1a14-11e7-8c6d-713857d31f65.png)

NOTE: It starts two process,which swallow about 1G memories for each.(I only have 8G memories, so I can't afford this) Every time you add `.` after `fs`, it starts one process.

Also @wsdjeg says`SpaceVim` shouldn't be blamed for this, and asked me to start a new issue here.
I don't know whether `SpaceVim` or `tern_for_vim` is to blames for.

Here's REF: https://github.com/SpaceVim/SpaceVim/issues/397

**Comment by marijnh** [comment]
>   loadEargely: ["**/*.js"]

This is probably the problem. If you're using CommonJS modules (which you seem to be), there's no need to load things eagerly. And if you have a huge dependency tree then yes, loading all of it eagerly is going to consume a lot of memory.

**Comment by Gabirel** [comment]
Thanks
