### ISSUE TITLE
Syntastic linting not recognizing filetype after tern_for_vim installation

### ISSUE THREAD

**Issue by deathbeam** [ternjs/tern_for_vim#177]
So, after I installed tern_for_vim, default filetype for javascript files was changed from `javascript` to `javascript.jsx`, what breaks Syntastic, because all checkers for javascript are made for `javascript` filetype.

**Comment by marijnh** [comment]
That doesn't sound like something this plugin does. In fact, the string `jsx` turns up zero hits when I grep for it in this repository.
