### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib;

### ISSUE THREAD

**Issue by odrzutowiec** [ternjs/tern_for_vim#197]
Hello, I woke up this morning, updated all my tools
```
1. brew update; brew upgrade; npm -g i npm; 
2. (inside vim using vim plugged) :PlugUpdate
3. (inside tern_for_vim) npm i
```

And then as usual proceeded to start editing a javascript file. When I opened the file following warning appeared:

```
Error detected while processing /Users/pyza/Projects/dotfiles/vim/plugged/tern_for_vim/autoload/tern.vim:
line    9:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

My stuff:
MacBook Air Mid 2012
macOS 10.13.5
Vim 8.1 (compiled Jul 5 2018 by Homebrew)
tern_for_vim 0.5.0 (checked inside package.json, but I run the most up to date version via Vim Plugged)

**Comment by jasongonzales23** [comment]
👍

**Comment by othree** [comment]
Use 8.1.0201 https://github.com/vim/vim/issues/3117#issuecomment-406868685

**Comment by odrzutowiec** [comment]
And for neovim what version?
