### ISSUE TITLE
Why doesn't it show me the write function of writerStream?

### ISSUE THREAD

**Issue by talkw-liu** [ternjs/tern_for_vim#199]
var fs = require("fs");
var rs = fs.createReadStream('./a.txt');
var ws = fs.createWriteStream('./copy.txt');
rs.on('data', function(chunk) {
    ws.write(chunk);
});

It does't show me the write funciton when i enter "ws.", and i only see some functions such as "bind,toString,valueOf...".I don't know why and i need some help.

**Comment by othree** [comment]
I believe this is a issue belongs to tern its self.
Could you move this issue to there, I will close this one?

ref: https://github.com/ternjs/tern/blob/master/plugin/node.js#L1740
