### ISSUE TITLE
TernRename renames object property with same name

### ISSUE THREAD

**Issue by Cyperwu** [ternjs/tern_for_vim#202]
```javascript
var a = 'foo'
var b = { a: 'bar' }

function c() {
  var d = 'buz'
  var e = a + b.a + d
  return e
}
```

With the code above, when I rename variable `a` with `foo`, the third line of function c will become `var e = foo + b.foo + d`

**Comment by othree** [comment]
I believe this is a tern issue. Could you open issue there.
