### ISSUE TITLE
Does not complete for node.js, or, how to set tern config globally?

### ISSUE THREAD

**Issue by unphased** [ternjs/tern_for_vim#57]
I'd really love for tern to complete node.js symbols for me because I am seriously tired of having the node docs open in my browser. 

I found that Tern has a node plugin, introduced [here](http://ternjs.net/doc/manual.html#plugin_node), but it seems like it's not enabled by tern_for_vim. 

How to enable it? Even cooler would be only to enable it if the file is detected as a node.js script. 

**Edit:** Looks like I need to use a `.tern-project` file to configure this. That will work but I wonder if this is is just too much of a pain. I am starting to write node scripts rather than writing shell scripts, and so they will literally start getting littered across my system, I would not be interested in having to also write little `.tern-project` files to support them as well. I would really prefer to be able to set a global setting (getting node completions in a browser js file is no big deal. the key is being able to get those completions)

**Comment by Pieter-Jan** [comment]
is this still valid?

**Comment by marijnh** [comment]
Yes.
