### ISSUE TITLE
Scratch window appears on completion

### ISSUE THREAD

**Issue by acthp** [ternjs/tern_for_vim#59]
In an empty directory, editing a new file, doing

```
a = {foo: 5}
a.<tab>
```

causes a scratch buffer to open at the top in a vertical split, with contents

```
number
```

With vim 7.4, on ubuntu. Happens even when the only plugins are tern_for_vim and YouCompleteMe.

**Comment by davepies** [comment]
thanks for that, had the same issue and that fixed it.
