### ISSUE TITLE
Tern Server fails to start

### ISSUE THREAD

**Issue by yoaquim** [ternjs/tern_for_vim#88]
Whenever I try and run a tern command, I get this:

```
Failed to start server:
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/yoaquim.cintron/.vim/bundle/tern_for_vim/node_modules/tern/bin/tern'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
Seldom will the server start correctly. 

The module is there, I'm assuming, but maybe there's an issue when loading it?

Any workarounds/fixes to this?

**Comment by marijnh** [comment]
If that absolute path is correct, I can see no reason why this would fail occasionally but not always. If you start `node` from the command line, and give it that path, does it work? Is there anything weird or non-deterministic about your file system (network mounts, etc)?

**Comment by yoaquim** [comment]
Not really. I installed this plugin by cloning via pathogen, and it's set up as a git submodule, since I back up my vim stuff to my own, personal repo. Running `node [path]` doesn't return an error.

**Comment by xavierartot** [comment]
same here.

**Comment by hatelove85911** [comment]
+1 same here.

**Comment by wuhong40** [comment]
I have the same issue. 
I modify the file autoload/tern.vim:L15 
from  
  let g:tern#command = ["node", expand('<sfile>:h') . '/../node_modules/tern/bin/tern', '--no-port-file']
to   
 let g:tern#command = ["nodejs", expand('<sfile>:h') . '/../node_modules/tern/bin/tern', '--no-port-file'].

My OS is Ubuntu 14.04. "node.js" command in Ubuntu is "nodejs" not "node", so can you add a option to set the command?
eg: let tern_nodejs_cmd = "nodejs"

**Comment by wuhong40** [comment]
Ubuntu "node.js" command is "nodejs" not "node". I works by modify autolad/tern.vim line 15 from
  let g:tern#command = ["node", expand('<sfile>:h') . '/../node_modules/tern/bin/tern', '--no-port-file']
to
  let g:tern#command = ["nodejs", expand('<sfile>:h') . '/../node_modules/tern/bin/tern', '--no-port-file'].
Can you add a option to set node.js command?
eg: let tern_nodejs_cmd = "nodejs"

**Comment by lekishvili** [comment]
I have same issue. Installed with Vundle

**Comment by lekishvili** [comment]
Solved problem with sudo npm install tern

**Comment by davidjb** [comment]
I installed this plugin via Vundle, and did a local install via ``npm install`` inside this plugin's directory (eg ``~/.vim/bundle/tern_for_vim``).  I can run the server standalone if I set with the NODE_PATH environment variable in the shell before opening vim to point it at ``~/.vim/bundle/tern_for_vim/node_modules``.  Need to look into this more for a better solution.

**Comment by collegeimprovements** [comment]
+1 same problem occurs on my mac also.

**Comment by twxia** [comment]
same problem here. Just need to go to `~/.vim/bundle/tern_for_vim/node_modules` 
`sudo npm install` myself

**Comment by mydearxym** [comment]
+1 same issue

**Comment by collegeimprovements** [comment]
I used neobundle and installed tern via sudo npm and still the issue persists.

**Comment by Zanadar** [comment]
@twxia Was having this problem, but your solution fixed it. :tada: (although in my case the path was `/.vim/plugged/tern_for_vim`

**Comment by marijnh** [comment]
(The fact that you have to `npm install` in the bundle's directory is mentioned in the readme.)

**Comment by Zanadar** [comment]
😳 yeah it's is. And I realized that things broke because I did a reinstall of all my plugins without running the install script. Shame on me.

**Comment by eshansingh** [comment]
Close?

**Comment by marijnh** [comment]
Let's.
